### ISSUE TITLE
Detect and use both disks

### ISSUE THREAD

**Issue by garloff** [osism/node-image#22]
The hard disks should be auto-detected by the node installer ...

**Comment by garloff** [comment]
Some code to output the full disk devices larger than 220GB:
```
IX=0; DISKS=()
while read dev majmin dum size rest; do 
  if [ $size -gt 220000000000 ]; then 
    DISKS[$IX]=$dev
    let IX+=1
  fi
done < <(lsblk -rb | grep disk | sort)
echo "${#DISKS[*]} disks: ${DISKS[*]}"
```

**Comment by berendt** [comment]
It is not possible to generate the disklayout on-the-fly, as this is permanently stored in the cloud init for Subiquity. Subiquity processes the user data and passes the disklayout to curtin.

You can remove the disklayout and query it via dialogue. But then you no longer have an automatic process and it no longer works headless.

**Comment by garloff** [comment]
OK, no way to generate the cloud-init yaml from a detection script?
I'd be happy to code something up ...
And yes, we want to keep things without required interaction.

**Comment by berendt** [comment]
Not without a lot of effort, because then you would have to turn the creation of the ISO upside down, as we are doing it at the moment. IMO not worth the effort for the case we are tackling with the Node Image and Cloud in a Box.
